services:

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - ALPACA_API_KEY=${ALPACA_API_KEY:-}
      - ALPACA_SECRET=${ALPACA_SECRET:-}

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend